-- Migration: Create did_you_know_cache table
-- Run this in the Supabase SQL Editor

-- Create the table
CREATE TABLE IF NOT EXISTS did_you_know_cache (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    book_title TEXT NOT NULL,
    book_author TEXT NOT NULL,
    insights JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(book_title, book_author)
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_did_you_know_cache_book
    ON did_you_know_cache(book_title, book_author);

-- Add RLS (Row Level Security) policies
ALTER TABLE did_you_know_cache ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read
CREATE POLICY "Allow authenticated read access" ON did_you_know_cache
    FOR SELECT TO authenticated
    USING (true);

-- Allow service role full access (for API operations)
CREATE POLICY "Allow service role full access" ON did_you_know_cache
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

-- Allow anon read/insert/update (for client-side caching)
CREATE POLICY "Allow anon read access" ON did_you_know_cache
    FOR SELECT TO anon
    USING (true);

CREATE POLICY "Allow anon insert access" ON did_you_know_cache
    FOR INSERT TO anon
    WITH CHECK (true);

CREATE POLICY "Allow anon update access" ON did_you_know_cache
    FOR UPDATE TO anon
    USING (true)
    WITH CHECK (true);

-- Comment explaining the table structure
COMMENT ON TABLE did_you_know_cache IS 'Cache for "Did you know?" insights generated by Grok AI for books';
COMMENT ON COLUMN did_you_know_cache.insights IS 'JSONB array of { rank: number, notes: [string, string, string] } objects';
